<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>BSDesigner.UtilitySystems</PackageId>
    <Title>BS Designer Utility Systems</Title>
    <Version>1.0.0</Version>
    <Authors>AlexGameDev</Authors>
    <RepositoryUrl>https://github.com/Alex-GameDev/BSDesigner</RepositoryUrl>
    <PackageReleaseNotes>Initial version</PackageReleaseNotes>
    <Description>Framework to design and execute Utility Systems as behaviour systems.</Description>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BSDesigner.Core\BSDesigner.Core.csproj" />
  </ItemGroup>
</Project>
