<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y &quot;$(ProjectDir)$(OutDir)$(TargetName)$(TargetExt)&quot; &quot;$(SolutionDir)bin&quot;" />
  </Target>

</Project>
